config/routes.rb
Rails.application.routes.draw do
  resources :versions
  resources :customers
  get 'home/index'
  root 'customers#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :version

  accepts_nested_attributes_for :version

  def self.search(search)
    if search
      joins(:version).where("customers.name LIKE ? or versions.description LIKE ?", "%#{search}%", "%#{search}%")
    else
      find(:all)
    end
  end
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.order(:name).page(params[:page]).per(10)
    if params[:search]
      @customers = Customer.search(params[:search]).order(:name).page(params[:page]).per(10)
    else
      @customers = Customer.all.order(:name).page(params[:page]).per(10)
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @customer.build_version
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_path, notice: "Cliente #{t('messages.created')}" }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customers_path, notice: "Cliente #{t('messages.updated')}" }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Cliente #{t('messages.destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, version_attributes: [:id, :description])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.all
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(version_params)

    respond_to do |format|
      if @version.save
        format.html { redirect_to @version, notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @version }
      else
        format.html { render :new }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to @version, notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: @version }
      else
        format.html { render :edit }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to versions_url, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:description, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Nome/Razão Social" %>
  </div>
  <%= f.fields_for :version do |version_fields| %>

    <div class="form-group">
      <%= version_fields.label :description %><br>
      <%= version_fields.text_field :description, class: "form-control", placeholder: "Versão" %>
    </div>

  <% end %>
  <div class="text-center">
    <%= link_to t('buttons.back'), customers_path, class: "btn btn-danger" %>
    <%= f.submit t('buttons.submit'), class: "btn btn-success" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1 class="text-center text-primary">Alterando Cliente</h1>

<div class="col-md-4 col-md-offset-4">
  <%= render 'form' %>
</div>

app/views/customers/index.html.erb
<p id="notice" class="text-center"><%= notice %></p>

<h1 class="text-center text-primary">App Versões</h1>

<hr>

<div class="col-md-6">
  <%= link_to t('buttons.new'), new_customer_path, class: "btn btn-primary" %>
</div>

<div class="col-md-6">
  <div class="form-group search-form">
    <%= form_tag(customers_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Razão Social/Versão", class: "form-control" %>
      <%= submit_tag t('buttons.search'), :name => nil, class: "btn btn-warning btn-search" %>
    <% end %>
  </div>
</div>

<% if @customers.blank? %>
  <h4>Sem resultados para: <%= params[:search] %></h4>
<% end %>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th><%= @customers.model.human_attribute_name("name") %></th>
      <th><%= @customers.model.human_attribute_name("version") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.version.description %></td>
        <td>
          <%= link_to t('buttons.edit'), edit_customer_path(customer), class: "btn btn-xs btn-info" %>
          <%= link_to t('buttons.destroy'), customer, method: :delete, data: { confirm: t('messages.confirm') }, class: "btn btn-xs btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= paginate @customers %>
</div>

app/views/customers/new.html.erb
<h1 class="text-center text-primary">Novo Cliente</h1>

<div class="col-md-4 col-md-offset-4">
  <%= render 'form' %>
</div>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/home/index.html.erb
<h1 class="text-center text-primary">Syclus-Versões</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App Versões</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/versions/_form.html.erb
<%= form_for(@version) do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/versions/edit.html.erb
<h1>Editing Version</h1>

<%= render 'form' %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Versions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.description %></td>
        <td><%= version.customer %></td>
        <td><%= link_to 'Show', version %></td>
        <td><%= link_to 'Edit', edit_version_path(version) %></td>
        <td><%= link_to 'Destroy', version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Version', new_version_path %>

app/views/versions/new.html.erb
<h1>New Version</h1>

<%= render 'form' %>

<%= link_to 'Back', versions_path %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @version.description %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @version.customer %>
</p>

<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', versions_path %>